### ISSUE TITLE
NullRefError TTS Menu

### ISSUE THREAD

**Issue by mati3230** [Cognigy/CognigyUnity3DClient#1]
I get a Null Reference Error when opening window "Window/Cognigy/TextToSpeech" in Script AcapelaTTSOptionsDrawer.cs Line 33. The field serviceOptions.VaasUrl is null.

**Comment by j-sommer** [comment]
Hi mati3230,

thank you for your feedback. I released a new version (1.0.2) which solves this issues.

**Comment by mati3230** [comment]
Hey Jan,

thank you - I will directly test it.

Best regards,

Marcel Tiator

2017-08-30 15:04 GMT+02:00 Jan Sommer <notifications@github.com>:
